export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const ADDUSER_REQUEST = "ADDUSER_REQUEST";
export const ADDUSER_SUCCESS = "ADDUSER_SUCCESS";
export const ADDUSER_FAILURE = "ADDUSER_FAILURE";

export const GET_USER = "GET_USER";
export const USER_RECIEVED = "USER_RECIEVED";

export const GET_POLLS = "GET_POLLS";
export const POLLS_RECIEVED = "POLLS_RECIEVED";

export const ADDPOLL_REQUEST = "ADDPOLL_REQUEST";
export const ADDPOLL_SUCCESS = "ADDPOLL_SUCCESS";
export const ADDPOLL_FAILURE = "ADDPOLL_FAILURE";

export const ADD_POLL = "ADD_POLL";
export const ADD_OPTION = "ADD_OPTION";

export const DELETEPOLL_REQUEST = "DELETEPOLL_REQUEST";
export const DELETEPOLL_SUCCESS = "DELETEPOLL_SUCCESS";

export const UPDATE_POLL = "UPDATE_POLL";
export const POLL_UPDATED = "POLL_UPDATED";
